/*
 * whyr.hpp
 *
 *  Created on: Sep 9, 2016
 *      Author: jrobbins
 */

#ifndef INCLUDE_WHYR_HPP_
#define INCLUDE_WHYR_HPP_

/**
 * This is the core WhyR file, included by all WhyR headers.
 * It contains imports needed by other headers, among other things.
 * 
 * TODO: Move the less essential imports out of here
 */

#include <llvm/Bitcode/ReaderWriter.h>
#include <llvm/IR/LLVMContext.h>
#include <llvm/Support/Casting.h>
#include <llvm/IR/Constants.h>
#include <llvm/IR/InstrTypes.h>
#include <llvm/IR/Instructions.h>
#include <llvm/ADT/SmallVector.h>
#include <llvm/Support/raw_ostream.h>

#include <string>
#include <fstream>
#include <iterator>
#include <vector>
#include <list>
#include <memory>
#include <iostream>

namespace whyr {
    using namespace std;
    using namespace llvm;
    
    class whyr_exception; class whyr_warning;
    
    /**
     * This structure keeps track of all the WhyR configuration settings.
     */
    struct WhyRSettings {
        /**
         * This enum represents how LLVM integers are represented in the Why3 models generated by generateWhy3.
         */
        enum Why3IntMode {
            /// Use Why3's Int type.
            WHY3_INT_MODE_INT,
            /// Use Why3's BV_Gen type.
            WHY3_INT_MODE_BV,
        } why3IntMode = WHY3_INT_MODE_INT;
        
        /**
         * This enum represents how LLVM floats are represented in the Why3 models generated by generateWhy3.
         */
        enum Why3FloatMode {
            /// Use Why3's Real type.
            WHY3_FLOAT_MODE_REAL,
            /// Use Why3's GenFloatSpecFull type.
            WHY3_FLOAT_MODE_FP,
        } why3FloatMode = WHY3_FLOAT_MODE_REAL;
        
        /**
         * This enum represents how the memory (and LLVM pointers) is represented in the Why3 models generated by generateWhy3.
         */
        enum Why3MemModel {
            /// The default memory model.
            WHY3_MEM_MODEL_DEFAULT,
            /// A minimalistic memory model unable to prove anything. Useful if your program does not use state.
            WHY3_MEM_MODEL_DUMMY,
        } why3MemModel = WHY3_MEM_MODEL_DEFAULT;
        
        ///  The list of errors generated during annotation.
        list<whyr_exception> errors;
        /// The list of warnings generated during annotation.
        list<whyr_warning> warnings;
        /// if true, treat all warnings as errors.
        bool werror = false;
        ///  If true, disable all warning output.
        bool noWarn = false;
        ///  If true, generate RTE assertions. See <whyr/rte.hpp> for details.
        bool rte = false;
        /// If true, no goals are generated, only theories.
        bool noGoals = false;
        /// If true, all goals are combined instead of split and copied.
        bool combineGoals = false;
    };
}


#endif /* INCLUDE_WHYR_HPP_ */
